services:
  - type: web
    name: socialitix-marketplace
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: INTASEND_API_PUBLISHABLE_KEY
        sync: false
      - key: INTASEND_API_SECRET_KEY
        sync: false
      - key: BASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false 